### ISSUE TITLE
Transform Address to coordinates

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/vot-romania-api#11]
This issue is related to #10 
When creating a new polling station (upload/create operation) the address of the polling station needs to be transformed into coordinates using HERE Maps API.

**Comment by idormenco** [comment]
in progress

**Comment by idormenco** [comment]
in progress

**Comment by RaduCStefanescu** [comment]
Hi @idormenco 
Did you manage to finish this issue?

**Comment by RaduCStefanescu** [comment]
Also, this one is done.
