### ISSUE TITLE
Display polling stations table

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/vot-romania-api#12]
As an admin I want to be able to see all the polling stations in a table on the admin panel.
The table should implement pagination and is searchable.
As an admin I can execute basic operations on the polling stations: create, delete, update.

**Comment by ancaspatariu** [comment]
Hey! I'd like to work on this.

**Comment by RaduCStefanescu** [comment]
All yours @ancaspatariu

**Comment by RaduCStefanescu** [comment]
@ancaspatariu did you get a chance to finish up the work on this issue? 
If so, would you be able to open a PR?
Thank you!

**Comment by ancaspatariu** [comment]
Unfortunately no, due to some issues I had with part of the tech stack, where I needed some more info. Sorry I forgot to unassigned myself.

**Comment by RaduCStefanescu** [comment]
Ok @ancaspatariu , thank you for the clarification!

**Comment by RaduCStefanescu** [comment]
This one is done.
