### ISSUE TITLE
Migrate database to postgresql 

### ISSUE THREAD

**Issue by idormenco** [code4romania/vot-romania-api#52]
Currently we are using sqlite but we need something more durable and reliable such as postgresql 

----
- get a hold of a functional postgres environment
    - docker would be the most accessible choice..
- add the postgresprovider
    - https://www.npgsql.org/efcore/index.html
- add the option to configure the connection string
- alter the VotRomaniaContext to use Postgres
- alter the register context to use Postgres
- add migrations for the existing database model
    - run those migrations successfully locally :)
- remove references to sqlite provider

**Comment by RaduCStefanescu** [comment]
This one is done.
